FROM python:3.11-slim

ENV PYTHONUNBUFFERED 1
ENV PYTHONDONTWRITEBYTECODE 1

WORKDIR /app 

RUN addgroup --system acad \
  && adduser --system --ingroup acad acad 

COPY requirements.txt /app/requirements.txt
RUN pip install --upgrade pip
RUN pip install setuptools wheel
RUN pip install -r requirements.txt
COPY --chown=acad:acad  . /app 


RUN chown acad:acad /app \
  && chmod -R 755 /app

ENV DJANGO_SETTINGS_MODULE=app.settings.test

USER acad

